source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'sqlite3'
gem 'erb_form', '0.1.1', :path => '../..'
gem 'simple_form', :git => 'git://github.com/plataformatec/simple_form'

group :development , :test  do
  gem 'rspec-rails'
  gem 'webrat'
end

